### ISSUE TITLE
Prod build fails on windows after upgrading systemjs-webpack-interop to v2.3.2

### ISSUE THREAD

**Issue by jiteshkrishnan** [joeldenning/systemjs-webpack-interop#17] opened 2020-12-15 14:49 UTC
Build fails with this new version 2.3.2 of systemjs-webpack-interop

**OS**
Windows 10
webpack v4.44.2
Node -v11.7
**Describe the bug or question**
The original issue was #15 , and when the fix was released yesterday as part of systemjs-webpack-interp@2.3.2, the webpack build process failed. 

Webpack build output
 2 assets
Entrypoint main = react-mf-planets.js react-mf-planets.js.map
 [0] external "react" 42 bytes {0} [built]
 [3] external "@react-mf/api" 42 bytes {0} [built]
 [7] (webpack)/buildin/global.js 472 bytes {0} [built]
[10] external "react-dom" 42 bytes {0} [built]
[11] external "rxjs" 42 bytes {0} [built]
[14] external "@react-mf/styleguide" 42 bytes {0} [built]
[15] multi ./D:/work/react/mfe/planets/node_modules/systemjs-webpack-interop/resource-query-public-path?systemjsModuleName=@react-mf/planets&rootDirectoryLevel=1 ./src/react-mf-planets.js 40 bytes {0} [built]
[20] (webpack)/buildin/module.js 497 bytes {0} [built]
[21] ./src/react-mf-planets.js + 17 modules 89.3 KiB {0} [built]
     | ./src/react-mf-planets.js 553 bytes [built]
     | ./src/set-public-path.js 93 bytes [built]
     | ./src/root.component.js 350 bytes [built]
     | ./src/planets-page/planets-page.component.js 5.59 KiB [built]
     | ./src/utils/api.js 736 bytes [built]
     | ./src/planet-list/planet-list.component.js 991 bytes [built]
     | ./src/planets-page/selected-planet/selected-planet.component.js 5.06 KiB [built]
     | ./src/planets-page/selected-planet/planet-attribute.component.js 476 bytes [built]
     | ./src/planets-page/selected-planet/notable-people/notable-people.component.js 3.5 KiB [built]
     |     + 9 hidden modules
    + 13 hidden modules

**ERROR in multi ./D:/work/react/mfe/planets/node_modules/systemjs-webpack-interop/resource-query-public-path?systemjsModuleName=@react-mf/planets&rootDirectoryLevel=1 ./src/react-mf-planets.js
Module not found: Error: Can't resolve 'D:\work\react\mfe\planets/D:\work\react\mfe\planets\node_modules\systemjs-webpack-interop/resource-query-public-path?systemjsModuleName=@react-mf/planets&rootDirectoryLevel=1' in 'D:\work\react\mfe\planets'
 @ multi ./D:/work/react/mfe/planets/node_modules/systemjs-webpack-interop/resource-query-public-path?systemjsModuleName=@react-mf/planets&rootDirectoryLevel=1 ./src/react-mf-planets.js main[0]**
Child HtmlWebpackCompiler:
     1 asset
    Entrypoint HtmlWebpackPlugin_0 = __child-HtmlWebpackPlugin_0
       1 module

This issue came up after upgrading 
webpack-config-single-spa ==>1.18.0.
webpack-config-single-spa-react ==>1.18.0.
and
systemjs-webpack-interop ==>2.3.2

**Comment by filoxo** [comment] 2020-12-15 16:13
Also reported on Slack:
- https://single-spa.slack.com/archives/C8R6U7MT7/p1608005922346800
- https://single-spa.slack.com/archives/C8R6U7MT7/p1608044852358300

**Comment by joeldenning** [comment] 2020-12-15 18:52
Turns out that my original fix in #16 didn't work. But the fix in #18 is confirmed to work, and is released in https://github.com/joeldenning/systemjs-webpack-interop/releases/tag/v2.3.3

**Closed by joeldenning** 2020-12-15 18:52 UTC
