### ISSUE TITLE
System.resolve returns promise, not string, how it can work

### ISSUE THREAD

**Issue by DmitryBrus** [joeldenning/systemjs-webpack-interop#7] opened 2020-04-08 12:10 UTC
I'm surprised how this tool can work properly,

since 
> moduleUrl = window.System.resolve(systemjsModuleName);

returns Promise and not a string 
https://github.com/systemjs/systemjs/issues/1909

Can somebody explain what I'm missing?

**Comment by joeldenning** [comment] 2020-04-08 18:14
This is a duplicate of https://github.com/systemjs/systemjs/issues/1909#issuecomment-610924557. I responded there.

**Closed by joeldenning** 2020-04-08 18:14 UTC

**Comment by DmitryBrus** [comment] 2020-04-08 20:59
Thank you, I appreciate your help a lot, might be worth to mention required System.js version in documentation, 
since out of the box systemjs-webpack-interop throws not clear error.

**Comment by joeldenning** [comment] 2020-04-08 21:14
The required SystemJS version is already listed in the readme at https://github.com/joeldenning/systemjs-webpack-interop#installation

> Note that systemjs-webpack-interop requires systemjs@>=6 and webpack@>=4.30.0

**Comment by DmitryBrus** [comment] 2020-04-08 21:18
@joeldenning 
You are absolutely right, I just missed it! thanks a lot!
